name: CI/CD pipline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare unit tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest ./tests/unit

      - name: Prepare integration tests
        run: |
          sudo docker run --name pg-tests -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres:16
          rm ./.env
          echo "AMQP_URL=$AMQP_URL
          POSTGRES_URL=$POSTGRES_URL
          " > .env
          sleep 5
          alembic upgrade head
        env:
          AMQP_URL: amqp://guest:guest123@51.250.26.59:5672/
          POSTGRES_URL: postgresql://postgres:password@localhost:5432/postgres

      - name: Run integration tests
        run: |
          PYTHONPATH=. pytest ./tests/integration
  build-and-push-to-yc:
    name: Build and push to YandexCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker thrift_products service image
        run: |
          docker build . --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/thrift_products:latest

      - name: Login to YandexCloud
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push thrift_products service image
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/thrift_products:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push-to-yc]
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-memory: 512Mb
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/thrift_products:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-env: |
            AMQP_URL=${{ secrets.ENV_AMQP_URL }}
            POSTGRES_URL=${{ secrets.ENV_POSTGRES_URL }}
