name: CI/CD pipline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push-to-yc:
    name: Build and push to YandexCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker thrift_products service image
        run: |
          docker build . --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/thrift_products:latest

      - name: Login to YandexCloud
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push thrift_products service image
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/thrift_products:latest
